# Generated by Django 4.1 on 2022-08-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentsid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sl_num', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('Reg_num', models.IntegerField()),
                ('Place', models.CharField(max_length=20)),
            ],
        ),
    ]
