# Generated by Django 4.1 on 2022-09-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_negister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
    ]
